### PR TITLE
fix: don't close client or server connection twice during alert handling

### LINKED ISSUE #53: Crash at client after successful handshake
Hello Jan

Here a new issue.

After a successful handshake and regular exchange of data between client and server, the client crashes with this message in the console:

`F/libc    ( 4545): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xd3e7ef20 in tid 27907 (2.ui), pid 4545 (.ptt.ptt_client)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/jfltexx/jflte:5.0.1/LRX22C/I9505XXUHQK1:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-03-14 21:49:29.752080152+0000
Process uptime: 101s
Cmdline: com.ptt.ptt_client
pid: 4545, tid: 27907, name: 2.ui  >>> com.ptt.ptt_client <<<
uid: 10128
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xd3e7ef20
    r0  b3e7ef00  r1  aef54220  r2  d3e7eefc  r3  07ffffff
    r4  80000000  r5  ffffffff  r6  b3e00540  r7  b3e01e50
    r8  b3e00380  r9  00000002  r10 b4224308  r11 b3e01e90
    ip  aef5422c  sp  7c8fb760  lr  0000001f  pc  aef670a8
backtrace:
      #00 pc 000370a8  /apex/com.android.runtime/lib/bionic/libc.so (arena_slab_reg_alloc+104) (BuildId: 44204e0c53d8b940de9ce87036b16471)
      #01 pc 00037665  /apex/com.android.runtime/lib/bionic/libc.so (je_arena_malloc_hard+376) (BuildId: 44204e0c53d8b940de9ce87036b16471)
      #02 pc 000309c1  /apex/com.android.runtime/lib/bionic/libc.so (je_malloc+1040) (BuildId: 44204e0c53d8b940de9ce87036b16471)
      #03 pc 0002c9a7  /apex/com.android.runtime/lib/bionic/libc.so (malloc+18) (BuildId: 44204e0c53d8b940de9ce87036b16471)
      #04 pc 0017b290  /data/app/~~h34K_ao9DgsUqVurL_NozQ==/com.ptt.ptt_client-YGK0p71IU5wqaxxrSpQMwA==/base.apk!libcrypto.so (CRYPTO_zalloc+96)`

This one happened after 1 minute and 30 seconds. But could get sometimes 4 hours without problem.

Will try to give you more input for this crash later ...

### PR DESCRIPTION
**Pull request by JKRhb**
Could resolve #53.

### CODE REVIEW

**Comment by Ifilehk** [comment]
OK trying a long running test with this fix.

Same should be done on server side too !!!

**Comment by JKRhb** [comment]
> OK trying a long running test with this fix.

Great! :) Hope that it resolves the problems. I also incorporated #55 into in this PR now.

> Same should be done on server side too !!!

Done :)

**Comment by JKRhb** [comment]
Potentially simplified the implementation now. Hope that the fix works :)

**Comment by JKRhb** [comment]
@Ifilehk I would merge this PR and release a new version now, please let me know if it has resolved #53 – if not feel free to reopen the issue :)

**Pull request merged**
